### ISSUE TITLE
"Как всё прошло" заменить на "Название события"

### ISSUE THREAD

**Issue by Lyumih** [hyoo-ru/survey.hyoo.ru#3]
<img width="780" alt="image" src="https://github.com/hyoo-ru/survey.hyoo.ru/assets/32732179/ac4299de-8c69-4636-b4ee-1534c4b16ed4">
На вопрос - "Как всё прошло?", ответ - хорошо, было весело, и т.п.
Такой вопрос вводит в заблуждение, т.к. по факту это название События/Мероприятия/Сайта.
"Название события" - Встреча в Питере или Отзыв на сайт "Встреча"

**Comment by nin-jin** [comment]
Поправил.
